config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  use_doorkeeper

  authenticated :admin do
    root to: 'admin/users#index', as: :authenticated_root
  end
  root to: redirect('/admins/sign_in')

  resources :confirm_emails

  namespace :admin do
    resources :users
    resources :events
    resources :performers
    resources :groups
    resources :venues
  end

  namespace :api do
    namespace :v1 do
      resources :users
      resources :venues
      resources :performers
      resources :group_performers
      resources :groups
      resources :news
      resources :activities
      resources :tickets do
        member do
          post :accept
          post :reject
        end
      end
      resources :events do
        resources :event_participants
      end
    end
  end

  get "callbacks/gmail", to: "callbacks#gmail"
  get "pages/gmail", to: "pages#gmail"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :credential, dependent: :destroy
  has_secure_password
  has_many :venues, dependent: :destroy
  has_many :performers, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :tickets, dependent: :destroy

  has_many :access_tokens, class_name: 'Doorkeeper::AccessToken',
                             foreign_key: :resource_owner_id,
                             dependent: :delete_all

  def get_valid_token
    Doorkeeper::AccessToken.where(resource_owner_id: id).each do |token|
      return token unless token.expired?
    end
    return nil
  end

  def full_name
    return first_name + ' ' + last_name
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @groups = Group.where(user_id: @user.id)
    @events = Event.where(user_id: @user.id)
    @performers = Performer.where(user_id: @user.id)
    @venues = Venue.where(user_id: @user.id)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  skip_before_action :doorkeeper_authorize!, only: [:create]

  def index
    users = User.all
    respond_with users
  end

  def show
    user = User.find(params[:id])
    respond_with user, serializer: UserSerializer
  end

  def create
    @user = User.new(user_params)
    form = UserCreateForm.new(@user)

    if form.validate(user_params)
      user = User.create(user_params)
      UserMailer.with(user: user).welcome_email.deliver_now
      render json: user
    else
      render json: form.errors, status: 422
    end
  end

  def update
    @user = User.find(params[:id])
    form = UserUpdateForm.new(@user)

    photo_params = Dropbox::UploadProcessor.new().(user_params[:base64_photo])

    @user.update(user_params.except(:base64_photo).merge(photo_params))
    render json: @user
  end

  def destroy
    User.destroy(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :base64_photo)
  end

end

app/views/admin/users/index.html.erb
<br>
<div class="card">
  <div class="card-header">
    USERS
  </div>
  <div class="card-body">
    <table class='table'>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
      </tr>
    <% @users.each do |user| %>
    <tr>
      <td>
              <%=link_to admin_user_path(user.id) do %>
               <%= user.id %>
             <% end %>
      </td>
      <td>   <%= user.full_name %></td>
      <td>   <%= user.email  %></td>
    </tr>
    <% end %>

    </table>

  </div>
</div>

app/views/admin/users/show.html.erb
<br>
<div class="card">
  <div class="card-header">
    <%= @user.full_name %>
  </div>
  <div class="card-body">
    Events:
    <table class='table'>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Created at</th>
      </tr>
    <% @events.each do |event| %>
    <tr>
      <td>
              <%=link_to admin_event_path(event.id) do %>
               <%= event.id %>
             <% end %>
      </td>
      <td>   <%= event.name %></td>
      <td>   <%= event.created_at  %></td>
    </tr>
    <% end %>

    </table>

    Performers
    <table class='table'>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Created at</th>
      </tr>
    <% @performers.each do |performer| %>
    <tr>
      <td>
              <%=link_to admin_performer_path(performer.id) do %>
               <%= performer.id %>
             <% end %>
      </td>
      <td>   <%= performer.name %></td>
      <td>   <%= performer.created_at  %></td>
    </tr>
    <% end %>

    </table>

    Groups
    <table class='table'>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Created at</th>
      </tr>
    <% @groups.each do |group| %>
    <tr>
      <td>
              <%=link_to admin_group_path(group.id) do %>
               <%= group.id %>
             <% end %>
      </td>
      <td>   <%= group.name %></td>
      <td>   <%= group.created_at  %></td>
    </tr>
    <% end %>

    </table>


    Venues
    <table class='table'>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Created at</th>
      </tr>
    <% @venues.each do |venue| %>
    <tr>
      <td>
              <%=link_to admin_venue_path(venue.id) do %>
               <%= venue.id %>
             <% end %>
      </td>
      <td>   <%= venue.name %></td>
      <td>   <%= venue.created_at  %></td>
    </tr>
    <% end %>

    </table>

  </div>
</div>