config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  use_doorkeeper

  authenticated :admin do
    root to: 'admin/users#index', as: :authenticated_root
  end
  root to: redirect('/admins/sign_in')

  resources :confirm_emails

  namespace :admin do
    resources :users
    resources :events
    resources :performers
    resources :groups
    resources :venues
  end

  namespace :api do
    namespace :v1 do
      resources :users
      resources :venues
      resources :performers
      resources :group_performers
      resources :groups
      resources :news
      resources :activities
      resources :tickets do
        member do
          post :accept
          post :reject
        end
      end
      resources :events do
        resources :event_participants
      end
    end
  end

  get "callbacks/gmail", to: "callbacks#gmail"
  get "pages/gmail", to: "pages#gmail"

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :object, polymorphic: true, foreign_type: 'resource_type', foreign_key: 'resource_id'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credential.rb
class Credential < ApplicationRecord
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_participants, dependent: :destroy
  has_many :activities, as: :object

  
  has_many :tickets
  belongs_to :user
  belongs_to :venue, optional: true

  def group_participants
    Group.where(id: self.event_participants.participant_groups.pluck(:resource_id))
  end

  def single_participants
    Performer.where(id: self.event_participants.single_participants.pluck(:resource_id))
  end

  def bio
    description
  end
end

app/models/event_participant.rb
class EventParticipant < ApplicationRecord
  scope :participant_groups, -> { where(resource_type: 'Group') }
  scope :single_participants, -> { where(resource_type: 'Performer') }


  belongs_to :resource, polymorphic: true
  belongs_to :event
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :activities, as: :object
  has_many :event_participants, as: :model
  has_many :group_performers
  has_many :performers, through: :group_performers, dependent: :destroy
  has_many :events, through: :event_participants

end

app/models/group_performer.rb
class GroupPerformer < ApplicationRecord
  belongs_to :group
  belongs_to :performer

  has_many :event_participants, -> { where(resource_type: "Group") }, class_name: "EventParticipant", foreign_key: 'resource_id'
  has_many :events, through: :event_participants
end

app/models/news_observer.rb
class NewsObserver < ActiveRecord::Observer
  observe :group, :venue, :event, :performer

  def after_create(record)
    Activity.create(resource_id: record.id, resource_type: record.class.name, user_id: record.user.id)
  end

end

app/models/performer.rb
class Performer < ApplicationRecord
  belongs_to :user
  has_many :activities, as: :object

  has_many :group_performers, dependent: :destroy
  has_many :groups, through: :group_performers

  has_many :event_participants, as: :model

  has_many :event_participants, -> { where(resource_type: "Performer") }, class_name: "EventParticipant", foreign_key: 'resource_id'
  has_many :events, through: :event_participants

  def full_name
    first_name + ' ' + last_name
  end

  def name
    full_name
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  belongs_to :user
  
  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :credential, dependent: :destroy
  has_secure_password
  has_many :venues, dependent: :destroy
  has_many :performers, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :tickets, dependent: :destroy

  has_many :access_tokens, class_name: 'Doorkeeper::AccessToken',
                             foreign_key: :resource_owner_id,
                             dependent: :delete_all

  def get_valid_token
    Doorkeeper::AccessToken.where(resource_owner_id: id).each do |token|
      return token unless token.expired?
    end
    return nil
  end

  def full_name
    return first_name + ' ' + last_name
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :user
  has_many :events
  has_many :activities, as: :object
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "admin"

  before_action :authenticate_admin!
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @groups = Group.where(user_id: @user.id)
    @events = Event.where(user_id: @user.id)
    @performers = Performer.where(user_id: @user.id)
    @venues = Venue.where(user_id: @user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < ActionController::API

  def gmail
    puts 'in the method'
    client = Gmail::Client.new({client_id: ENV['GOOGLE_CLIENT_ID'] , client_secret: ENV['GOOGLE_CLIENT_SECRET'], redirect_uri: ENV['GOOGLE_REDIRECT_URI']})
    client.authenticate({code: params[:code]})
    user_attributes = client.get_logged_in_user

    user = User.find_by(email: user_attributes[:email]) || User::GmailCreateOperation.new(user_attributes.merge({ access_token: client.access_token })).()

    token = user.get_valid_token || Token::CreateInteractor.new(user).()

    redirect_to "https://www.9gag.com"

  end
end

app/controllers/confirm_emails_controller.rb
class ConfirmEmailsController < ApplicationController
  def index
    @user = User.find_by(confirmation_token: params[:token])
    @user.update(confirmation_token: nil, confirmation_sent_at: nil, confirmed_at: DateTime.now)
    render "index"
  end
end

app/controllers/pages_controller.rb
class PagesController < ActionController::API
  def gmail
    permissions = %w{
    https://www.googleapis.com/auth/userinfo.email
    https://www.googleapis.com/auth/userinfo.profile
    https://www.googleapis.com/auth/plus.login
  }

  # access token is users access token se we can identify to whom we should assign

  redirect_to "https://accounts.google.com/o/oauth2/auth?response_type=code&access_type=offline&client_id=%{client_id}&redirect_uri=%{redirect_uri}&scope=%{scope}&approval_prompt=force" % {
    client_id: ENV["GOOGLE_CLIENT_ID"],
    redirect_uri: ENV["GOOGLE_REDIRECT_URI"],
    scope: permissions.join('+'),
  }

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bio_resolver(bio)
    return bio if object.bio.length < 180
    return bio[0..180].gsub(/\s\w+\s*$/,'...') unless !object.bio.present?
    'Missing'
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard</title>

    <style>
      #loader {
        transition: all 0.3s ease-in-out;
        opacity: 1;
        visibility: visible;
        position: fixed;
        height: 100vh;
        width: 100%;
        background: #fff;
        z-index: 90000;
      }

      #loader.fadeOut {
        opacity: 0;
        visibility: hidden;
      }

      .spinner {
        width: 40px;
        height: 40px;
        position: absolute;
        top: calc(50% - 20px);
        left: calc(50% - 20px);
        background-color: #333;
        border-radius: 100%;
        -webkit-animation: sk-scaleout 1.0s infinite ease-in-out;
        animation: sk-scaleout 1.0s infinite ease-in-out;
      }

      @-webkit-keyframes sk-scaleout {
        0% { -webkit-transform: scale(0) }
        100% {
          -webkit-transform: scale(1.0);
          opacity: 0;
        }
      }

      @keyframes sk-scaleout {
        0% {
          -webkit-transform: scale(0);
          transform: scale(0);
        } 100% {
          -webkit-transform: scale(1.0);
          transform: scale(1.0);
          opacity: 0;
        }
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Event World Admin </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%=link_to admin_users_path, :class => "nav-link" do %>
            Users
        <% end %>
      </li>
      <li class="nav-item">
        <%=link_to admin_events_path, :class => "nav-link" do %>
            Events
        <% end %>
      </li>
      <li class="nav-item">
        <%=link_to admin_venues_path, :class => "nav-link" do %>
            Venues
        <% end %>
      </li>
      <li class="nav-item">
        <%=link_to admin_groups_path, :class => "nav-link" do %>
            Groups
        <% end %>
      </li>
      <li class="nav-item">
        <%=link_to admin_performers_path, :class => "nav-link" do %>
            Performers
        <% end %>
      </li>
    </ul>
  </div>
  <ul class='navbar-nav pull-right'>
    <li class="nav-item">
    <%= link_to('Logout', destroy_admin_session_path, method: :delete) %>
    </li>
  </ul>
</nav>
<div class="container">
  <%= yield %>
</div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackendSdp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>